/*
 * Card recognition algorithm — the port of tools/pipeline.py.
 *
 * Kept free of worker/DOM APIs so it can be exercised head-first in Node against fixtures
 * generated by the Python harness (see tools/test_worker_js.js). js/recognizer.worker.js
 * is a thin transport wrapper around this.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.RecognizerCore = factory();
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const MIN_ASPECT = 1.25;
  const MAX_ASPECT = 2.20;
  const MIN_AREA_FRAC = 0.010;
  const MAX_AREA_FRAC = 0.60;
  const DEDUPE_DIST = 40;
  const MAX_QUADS = 6;

  function dist(a, b) { return Math.hypot(a[0] - b[0], a[1] - b[1]); }

  function centroid(corners) {
    let x = 0; let y = 0;
    for (const c of corners) { x += c[0]; y += c[1]; }
    return [x / corners.length, y / corners.length];
  }

  /** Order 4 points as top-left, top-right, bottom-right, bottom-left. */
  function orderCorners(data32S) {
    const pts = [];
    for (let i = 0; i < 4; i += 1) pts.push([data32S[i * 2], data32S[i * 2 + 1]]);
    let tl = pts[0]; let br = pts[0]; let tr = pts[0]; let bl = pts[0];
    let minSum = Infinity; let maxSum = -Infinity;
    let minDiff = Infinity; let maxDiff = -Infinity;
    for (const p of pts) {
      const sum = p[0] + p[1];
      const diff = p[1] - p[0];
      if (sum < minSum) { minSum = sum; tl = p; }
      if (sum > maxSum) { maxSum = sum; br = p; }
      if (diff < minDiff) { minDiff = diff; tr = p; }
      if (diff > maxDiff) { maxDiff = diff; bl = p; }
    }
    return [tl, tr, br, bl];
  }

  /**
   * Build a recognizer bound to an OpenCV instance and a loaded card database.
   * @param cv   the initialised opencv.js module
   * @param db   { params, entries, descriptors: cv.Mat, keypoints: Float32Array[], ownerOf }
   */
  function createRecognizer(cv, db) {
    const p = db.params;
    const orb = new cv.ORB(p.queryFeatures || p.nfeatures, p.scaleFactor, p.nlevels, 31, 0, 2,
      cv.ORB_HARRIS_SCORE, 31, p.fastThreshold);
    const matcher = new cv.BFMatcher(cv.NORM_HAMMING, false);
    const clahe = new cv.CLAHE(2.0, new cv.Size(8, 8));

    function findCardQuads(gray, width, height) {
      const frameArea = width * height;
      const blurred = new cv.Mat();
      cv.GaussianBlur(gray, blurred, new cv.Size(5, 5), 0);

      const masks = [];
      const edges = new cv.Mat();
      cv.Canny(blurred, edges, 40, 120);
      const kernel = cv.Mat.ones(3, 3, cv.CV_8U);
      cv.dilate(edges, edges, kernel);
      kernel.delete();
      masks.push(edges);

      const adaptive = new cv.Mat();
      cv.adaptiveThreshold(blurred, adaptive, 255, cv.ADAPTIVE_THRESH_MEAN_C,
        cv.THRESH_BINARY_INV, 31, 8);
      masks.push(adaptive);
      blurred.delete();

      const found = [];
      for (const mask of masks) {
        const contours = new cv.MatVector();
        const hierarchy = new cv.Mat();
        cv.findContours(mask, contours, hierarchy, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE);
        for (let i = 0; i < contours.size(); i += 1) {
          const contour = contours.get(i);
          const area = cv.contourArea(contour);
          if (area > MIN_AREA_FRAC * frameArea && area < MAX_AREA_FRAC * frameArea) {
            const approx = new cv.Mat();
            cv.approxPolyDP(contour, approx, 0.02 * cv.arcLength(contour, true), true);
            if (approx.rows === 4 && cv.isContourConvex(approx)) {
              const corners = orderCorners(approx.data32S);
              const w = (dist(corners[1], corners[0]) + dist(corners[2], corners[3])) / 2;
              const h = (dist(corners[3], corners[0]) + dist(corners[2], corners[1])) / 2;
              const aspect = h / w;
              if (w > 20 && h > 20 && aspect > MIN_ASPECT && aspect < MAX_ASPECT) {
                found.push({ area, corners });
              }
            }
            approx.delete();
          }
          contour.delete();
        }
        contours.delete();
        hierarchy.delete();
        mask.delete();
      }

      // The two detectors usually find the same card twice — keep the largest per cluster.
      found.sort((a, b) => b.area - a.area);
      const kept = [];
      for (const candidate of found) {
        const centre = centroid(candidate.corners);
        if (kept.some((k) => dist(centroid(k), centre) < DEDUPE_DIST)) continue;
        kept.push(candidate.corners);
        if (kept.length >= MAX_QUADS) break;
      }
      return kept;
    }

    function rectify(gray, corners) {
      const W = p.canonWidth;
      const H = p.canonHeight;
      const src = cv.matFromArray(4, 1, cv.CV_32FC2, [
        corners[0][0], corners[0][1], corners[1][0], corners[1][1],
        corners[2][0], corners[2][1], corners[3][0], corners[3][1],
      ]);
      const dst = cv.matFromArray(4, 1, cv.CV_32FC2, [0, 0, W, 0, W, H, 0, H]);
      const transform = cv.getPerspectiveTransform(src, dst);
      const out = new cv.Mat();
      cv.warpPerspective(gray, out, transform, new cv.Size(W, H));
      src.delete(); dst.delete(); transform.delete();
      return out;
    }

    /**
     * Rank all cards by a cheap appearance signature and return the most likely ones.
     * Brute-force descriptor matching then only has to consider these, which is where
     * nearly all of the frame budget used to go.
     */
    function shortlist(grayCanonical) {
      const dims = db.signatureDims;
      const small = new cv.Mat();
      cv.resize(grayCanonical, small, new cv.Size(p.sigWidth, p.sigHeight), 0, 0,
        cv.INTER_AREA);

      const query = new Float32Array(dims);
      let mean = 0;
      for (let i = 0; i < dims; i += 1) { query[i] = small.data[i]; mean += query[i]; }
      mean /= dims;
      let norm = 0;
      for (let i = 0; i < dims; i += 1) { query[i] -= mean; norm += query[i] * query[i]; }
      norm = Math.sqrt(norm);
      if (norm > 1e-6) for (let i = 0; i < dims; i += 1) query[i] /= norm;
      small.delete();

      // Two rows per card (upright, reversed); keep whichever orientation scores higher.
      const best = new Float32Array(db.entries.length).fill(-Infinity);
      for (let row = 0; row < db.signatureRows; row += 1) {
        const base = row * dims;
        let score = 0;
        for (let i = 0; i < dims; i += 1) score += db.signatures[base + i] * query[i];
        const card = row >> 1;
        if (score > best[card]) best[card] = score;
      }

      return Array.from(best.keys())
        .sort((a, b) => best[b] - best[a])
        .slice(0, p.shortlist || 12);
    }

    /**
     * Assemble one descriptor matrix from the shortlisted cards, plus the lookup tables
     * needed to map a row of it back to (card, keypoint).
     */
    function buildSubset(candidates) {
      let rows = 0;
      for (const cardIndex of candidates) rows += db.entries[cardIndex].count;

      const data = new Uint8Array(rows * 32);
      const owner = new Int32Array(rows);
      const local = new Int32Array(rows);

      let at = 0;
      for (const cardIndex of candidates) {
        const entry = db.entries[cardIndex];
        data.set(db.raw.subarray(entry.offset * 32, (entry.offset + entry.count) * 32), at * 32);
        for (let i = 0; i < entry.count; i += 1) {
          owner[at + i] = cardIndex;
          local[at + i] = i;
        }
        at += entry.count;
      }
      return { mat: cv.matFromArray(rows, 32, cv.CV_8U, data), owner, local };
    }

    function verify(cardIndex, pairs, queryKeypoints) {
      const kp = db.keypoints[cardIndex];
      const srcData = new Float32Array(pairs.length * 2);
      const dstData = new Float32Array(pairs.length * 2);

      pairs.forEach(([queryIdx, local], i) => {
        srcData[i * 2] = kp[local * 2];
        srcData[i * 2 + 1] = kp[local * 2 + 1];
        const point = queryKeypoints.get(queryIdx).pt;
        dstData[i * 2] = point.x;
        dstData[i * 2 + 1] = point.y;
      });

      const src = cv.matFromArray(pairs.length, 1, cv.CV_32FC2, srcData);
      const dst = cv.matFromArray(pairs.length, 1, cv.CV_32FC2, dstData);
      const mask = new cv.Mat();
      const homography = cv.findHomography(src, dst, cv.RANSAC, p.ransacReproj, mask);

      let inliers = 0;
      if (!homography.empty()) {
        for (let i = 0; i < mask.rows; i += 1) inliers += mask.data[i] ? 1 : 0;
      }

      // Upright or reversed, according to the rotation the homography applies.
      let reversed = false;
      if (!homography.empty() && homography.rows === 3) {
        const h = homography.data64F;
        reversed = Math.abs(Math.atan2(h[3], h[0])) > Math.PI / 2;
      }

      src.delete(); dst.delete(); mask.delete(); homography.delete();
      return { inliers, reversed };
    }

    function matchCard(grayCard, wholeFrame) {
      const equalised = new cv.Mat();
      clahe.apply(grayCard, equalised);

      const keypoints = new cv.KeyPointVector();
      const descriptors = new cv.Mat();
      const noMask = new cv.Mat();
      orb.detectAndCompute(equalised, noMask, keypoints, descriptors);
      noMask.delete();
      equalised.delete();

      if (descriptors.rows < 12) {
        keypoints.delete(); descriptors.delete();
        return null;
      }

      // Only the shortlisted cards go into the brute-force match. The whole-frame fallback
      // has no rectified card to take a signature from, so it searches everything.
      const subset = wholeFrame ? null : buildSubset(shortlist(grayCard));
      const train = subset ? subset.mat : db.descriptors;

      const knn = new cv.DMatchVectorVector();
      matcher.knnMatch(descriptors, train, knn, 2);

      // Lowe ratio test, then vote for the card each surviving match points at.
      const votes = new Map();
      for (let i = 0; i < knn.size(); i += 1) {
        const pair = knn.get(i);
        if (pair.size() >= 2) {
          const best = pair.get(0);
          const second = pair.get(1);
          if (best.distance < p.ratio * second.distance) {
            const owner = subset ? subset.owner[best.trainIdx] : db.ownerOf[best.trainIdx];
            const local = subset
              ? subset.local[best.trainIdx]
              : best.trainIdx - db.entries[owner].offset;
            if (!votes.has(owner)) votes.set(owner, []);
            votes.get(owner).push([best.queryIdx, local]);
          }
        }
        pair.delete();
      }
      knn.delete();
      if (subset) subset.mat.delete();

      const ranked = [...votes.entries()]
        .sort((a, b) => b[1].length - a[1].length)
        .slice(0, p.topCandidates);

      let best = null;
      let runnerUp = 0;
      for (const [cardIndex, pairs] of ranked) {
        if (pairs.length < 8) continue;
        const verified = verify(cardIndex, pairs, keypoints);
        if (!best || verified.inliers > best.inliers) {
          if (best) runnerUp = best.inliers;
          best = { cardIndex, inliers: verified.inliers, reversed: verified.reversed };
        } else if (verified.inliers > runnerUp) {
          runnerUp = verified.inliers;
        }
      }

      keypoints.delete();
      descriptors.delete();

      if (!best) return null;
      const margin = best.inliers - runnerUp;
      // The whole-frame fallback is noisier, so hold it to a stricter bar.
      const minInliers = wholeFrame ? p.minInliers + 3 : p.minInliers;
      if (best.inliers < minInliers || margin < p.minMargin) return null;

      return {
        id: db.entries[best.cardIndex].id,
        inliers: best.inliers,
        margin,
        reversed: best.reversed,
      };
    }

    /**
     * Recognise cards in one RGBA frame.
     *
     * Matching is the expensive step, so live scanning matches only `maxMatches` quads per
     * frame starting at `startIndex`, rotating through them across successive frames. Quad
     * detection is cheap and always runs on every quad, so the overlay stays live even when
     * a card is not being matched this time round.
     *
     * @returns {{quads: Array, cards: Array}}
     */
    function processFrame(rgba, width, height, options) {
      const opts = options || {};
      const maxMatches = opts.maxMatches > 0 ? opts.maxMatches : Infinity;
      const startIndex = opts.startIndex || 0;

      const src = cv.matFromArray(height, width, cv.CV_8UC4, rgba);
      const gray = new cv.Mat();
      cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY);
      src.delete();

      const cards = [];
      let quads = [];
      try {
        quads = findCardQuads(gray, width, height);

        const budget = Math.min(maxMatches, quads.length);
        for (let n = 0; n < budget; n += 1) {
          const quad = quads[(startIndex + n) % quads.length];
          const rectified = rectify(gray, quad);
          const match = matchCard(rectified, false);
          rectified.delete();
          if (match) {
            match.corners = quad;
            cards.push(match);
          }
        }

        // Fallback: nothing card-shaped found, so try matching the frame as a whole.
        if (quads.length === 0) {
          const match = matchCard(gray, true);
          if (match) {
            match.corners = null;
            cards.push(match);
          }
        }
      } finally {
        gray.delete();
      }
      return { quads, cards };
    }

    return { processFrame, findCardQuads, rectify, matchCard };
  }

  /** Turn the fetched database files into the structure createRecognizer expects. */
  function buildDatabase(cv, meta, binaryBuffer, signatureBuffer) {
    const bytes = new Uint8Array(binaryBuffer);
    const descriptors = cv.matFromArray(meta.total, meta.descriptorBytes, cv.CV_8U, bytes);

    const ownerOf = new Int32Array(meta.total);
    meta.cards.forEach((entry, index) => {
      ownerOf.fill(index, entry.offset, entry.offset + entry.count);
    });

    const keypoints = meta.cards.map((entry) => {
      const flat = new Float32Array(entry.kp.length * 2);
      for (let i = 0; i < entry.kp.length; i += 1) {
        flat[i * 2] = entry.kp[i][0];
        flat[i * 2 + 1] = entry.kp[i][1];
      }
      return flat;
    });

    return {
      params: meta.params,
      entries: meta.cards,
      descriptors,
      raw: bytes,
      keypoints,
      ownerOf,
      signatures: new Float32Array(signatureBuffer),
      signatureRows: meta.signatureRows,
      signatureDims: meta.signatureDims,
    };
  }

  return { createRecognizer, buildDatabase };
}));
